---
title: "nita"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = NA,
  echo = TRUE,
  error = TRUE,
  cache = FALSE,
  message = FALSE,
  dpi = 144,
  warning = FALSE
)
```

set up
```{r}
library(readxl)
library(tidyverse)
library(dplyr)
library(lubridate)
data = read.csv("Data/cleaned_data.csv")
```

data preprocessing
```{r}
data$Time = as.character(data$Time.Aired)
data$Time = hms::as_hms(data$Time)
dat <- data %>%
  select(-X) %>%
  mutate(hour = hour(Time))
dat$hour = as.factor(dat$hour)
dat$Access = as.factor(dat$Access)
dat$Estimate = as.factor(dat$Estimate)
dat$Market = as.factor(dat$Market)
dat$Spot.Type = as.factor(dat$Spot.Type)
dat$week = weekdays(as.Date(dat$Date.Aired, '%Y-%m-%d'))

uni <- read_excel("Data/station universe.xlsx")
uni$Station.ID = as.integer(uni$`Station ID`)

dat2 <- dat %>%
  left_join(uni, by = "Station.ID")
colnames(dat2)[19] = 'subscribers'
dat2 <- dat2 %>%
  mutate(absolute_audience_size = subscribers * GRP) %>%
  select(-`Station ID`)

## remove outliers
outliers_station = c('216', '184', '352', '311', '200', '10', '15', '192', '224', '280', '252', '72')
df <- dat2 %>%
  mutate(outlier = ifelse(Station.ID %in% outliers_station, 1, 0))
unseen = df %>%
  filter(GRP == 0)
training = df %>%
  filter(GRP > 0)
```

model training, data split
```{r}
install.packages("randomForest")
library(randomForest)

set.seed(1234)
train <- sample(nrow(training), 0.7*nrow(training), replace = FALSE)
TrainSet <- training[train,]
ValidSet <- training[-train,]
summary(TrainSet)
summary(ValidSet)
Train <- TrainSet %>%
  select(-Date.Aired, -DMA, -Media, -Time.Aired, -Time, -GRP)
Train$outlier = as.factor(Train$outlier)

Val <- ValidSet %>%
  select(-Date.Aired, -DMA, -Media, -Time.Aired, -Time, -GRP)
Val$outlier = as.factor(Val$outlier)

#write.csv(Train, 'nitarftrain.csv')
```

##Cross Validation
```{r}
library(radiant)
result <- rforest(
  Train, 
  rvar = "absolute_audience_size", 
  evar = c(
    "Length", "Estimate", "Market", "Spot.Cost", 
    "Station.ID", "week", "hour", "outlier"
  ), 
  type = "regression",
  seed = 1234
)
cv.rforest(
  result, K = 5, mtry = 1:3, min.node.size = seq(1, 10, 5),
  num.trees = c(100, 200), fun = RMSE
)
```

## Final Model
```{r fig.width = 7, fig.height = 4.85, dpi = 96}
library(radiant)
result <- rforest(
  Train, 
  rvar = "absolute_audience_size", 
  evar = c(
    "Length", "Estimate", "Market", "Spot.Cost", 
    "Station.ID", "week", "hour", "outlier"
  ), 
  type = "regression",
  seed = 1234, mtry = 3, min.node.size = 1, num.trees = 200
)
summary(result)
plot(result, plots = "vimp", custom = FALSE)

pred <- predict(result, pred_data = Train)
print(pred, n = 10)
Train <- store(Train, pred, name = "pred_rf") %>%
  mutate(se = ((absolute_audience_size - pred_rf)^2))

pred2 <- predict(result, pred_data = Val)
print(pred2, n = 10)
Val <- store(Val, pred2, name = "pred_rf") %>%
  mutate(se = ((absolute_audience_size - pred_rf)^2))

mse_train = mean(Train$se)
mse_train

mse_val = mean(Val$se)
mse_val
```

```{r}
print(paste0("The MSE for training set is, ", mse_train))
print(paste0("The MSE for validation set is, ", mse_val))
Traintable <- Train %>%
  select(-Spot.Type)
```
